"""add fcm_token to users

Revision ID: 43aa16ff3dd5
Revises: 5f81d022f1e0
Create Date: 2025-05-16 08:31:29.303965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43aa16ff3dd5'
down_revision: Union[str, None] = '5f81d022f1e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_requests', sa.Column('is_paid', sa.Boolean(), nullable=True))
    op.add_column('client_requests', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client_requests', 'payments', ['payment_id'], ['id'])
    op.add_column('users', sa.Column('fcm_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fcm_token')
    op.drop_constraint(None, 'client_requests', type_='foreignkey')
    op.drop_column('client_requests', 'payment_id')
    op.drop_column('client_requests', 'is_paid')
    # ### end Alembic commands ###
