"""add device_id to users

Revision ID: 48faa8b8419d
Revises: 594c4ff6600f
Create Date: 2025-05-17 11:32:04.979270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48faa8b8419d'
down_revision: Union[str, None] = '594c4ff6600f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('device_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('device_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['device_id'])
    op.drop_column('users', 'fcm_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fcm_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'device_id')
    op.drop_column('users', 'device_token')
    # ### end Alembic commands ###
