"""add payments table

Revision ID: 957a1740a27f
Revises: 48faa8b8419d
Create Date: 2025-05-17 14:10:44.810364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957a1740a27f'
down_revision: Union[str, None] = '48faa8b8419d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('purpose', sa.String(), nullable=False))
    op.alter_column('payments', 'package_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'times_per_day',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'times_per_day',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'package_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('payments', 'purpose')
    # ### end Alembic commands ###
