"""add status and bank to payments

Revision ID: a33c28e9f71d
Revises: 1562100f91e3
Create Date: 2025-05-15 11:11:13.313770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a33c28e9f71d'
down_revision: Union[str, None] = '1562100f91e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paid_packages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paid_packages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('boosts_per_day', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='paid_packages_pkey'),
    sa.UniqueConstraint('name', name='paid_packages_name_key')
    )
    # ### end Alembic commands ###
